import { MenuItem, MenuCategory } from '@/types'

export const CATEGORIES: MenuCategory[] = [
  { id: 'cat-1', name: 'Kopi', sortOrder: 1 },
  { id: 'cat-2', name: 'Non-Kopi', sortOrder: 2 },
  { id: 'cat-3', name: 'Makanan', sortOrder: 3 },
  { id: 'cat-4', name: 'Snack', sortOrder: 4 },
]

export const MENU_ITEMS: MenuItem[] = [
  // Kopi
  {
    id: 'menu-1',
    name: 'Es Kopi Susu',
    description: 'Espresso, susu segar, dan es batu. Klasik, segar, dan kaya rasa.',
    price: 18000,
    category: 'Kopi',
    categoryId: 'cat-1',
    imageEmoji: '☕',
    isAvailable: true,
  },
  {
    id: 'menu-2',
    name: 'Americano',
    description: 'Espresso double shot dengan air panas. Pahit sempurna.',
    price: 15000,
    category: 'Kopi',
    categoryId: 'cat-1',
    imageEmoji: '🖤',
    isAvailable: true,
  },
  {
    id: 'menu-3',
    name: 'Cappuccino',
    description: 'Espresso dengan foam susu tebal. Klasik Italia.',
    price: 22000,
    category: 'Kopi',
    categoryId: 'cat-1',
    imageEmoji: '☕',
    isAvailable: true,
  },
  {
    id: 'menu-4',
    name: 'Latte',
    description: 'Espresso lembut dengan susu steam berlimpah.',
    price: 22000,
    category: 'Kopi',
    categoryId: 'cat-1',
    imageEmoji: '🥛',
    isAvailable: true,
  },
  {
    id: 'menu-5',
    name: 'Kopi Tubruk',
    description: 'Kopi tradisional Indonesia, diseduh langsung tanpa filter.',
    price: 10000,
    category: 'Kopi',
    categoryId: 'cat-1',
    imageEmoji: '☕',
    isAvailable: true,
  },
  // Non-Kopi
  {
    id: 'menu-6',
    name: 'Matcha Latte',
    description: 'Matcha premium Jepang dengan susu segar. Earthy dan creamy.',
    price: 25000,
    category: 'Non-Kopi',
    categoryId: 'cat-2',
    imageEmoji: '🍵',
    isAvailable: true,
  },
  {
    id: 'menu-7',
    name: 'Coklat Susu',
    description: 'Cokelat belgique rich dengan susu panas atau dingin.',
    price: 20000,
    category: 'Non-Kopi',
    categoryId: 'cat-2',
    imageEmoji: '🍫',
    isAvailable: true,
  },
  {
    id: 'menu-8',
    name: 'Es Teh Manis',
    description: 'Teh hitam segar dengan gula aren. Segar dan ringan.',
    price: 8000,
    category: 'Non-Kopi',
    categoryId: 'cat-2',
    imageEmoji: '🧋',
    isAvailable: true,
  },
  {
    id: 'menu-9',
    name: 'Jus Alpukat',
    description: 'Alpukat segar blended dengan susu dan cokelat.',
    price: 20000,
    category: 'Non-Kopi',
    categoryId: 'cat-2',
    imageEmoji: '🥑',
    isAvailable: false,
  },
  // Makanan
  {
    id: 'menu-10',
    name: 'Nasi Goreng Spesial',
    description: 'Nasi goreng dengan telur, ayam suwir, dan acar. Favorit pelanggan.',
    price: 28000,
    category: 'Makanan',
    categoryId: 'cat-3',
    imageEmoji: '🍳',
    isAvailable: true,
  },
  {
    id: 'menu-11',
    name: 'Mie Goreng',
    description: 'Mie goreng dengan sayuran segar dan bumbu spesial.',
    price: 25000,
    category: 'Makanan',
    categoryId: 'cat-3',
    imageEmoji: '🍜',
    isAvailable: true,
  },
  {
    id: 'menu-12',
    name: 'Roti Bakar Selai',
    description: 'Roti tawar panggang dengan pilihan selai cokelat atau kacang.',
    price: 15000,
    category: 'Makanan',
    categoryId: 'cat-3',
    imageEmoji: '🍞',
    isAvailable: true,
  },
  // Snack
  {
    id: 'menu-13',
    name: 'Kentang Goreng',
    description: 'Kentang goreng crispy dengan saus sambal dan mayo.',
    price: 18000,
    category: 'Snack',
    categoryId: 'cat-4',
    imageEmoji: '🍟',
    isAvailable: true,
  },
  {
    id: 'menu-14',
    name: 'Pisang Goreng Keju',
    description: 'Pisang goreng crispy taburan keju parut dan susu kental.',
    price: 15000,
    category: 'Snack',
    categoryId: 'cat-4',
    imageEmoji: '🍌',
    isAvailable: true,
  },
]

export function formatRupiah(price: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
  }).format(price)
}
