import { MenuItem, MenuCategory } from '@/types'

export const CATEGORIES: MenuCategory[] = [
  { id: 'cat-1', name: 'Kopi', sortOrder: 1 },
  { id: 'cat-2', name: 'Non-Kopi', sortOrder: 2 },
  { id: 'cat-3', name: 'Makanan', sortOrder: 3 },
  { id: 'cat-4', name: 'Snack', sortOrder: 4 },
]

export const MENU_ITEMS: MenuItem[] = [
  // Kopi
  {
    id: 'menu-1',
    name: 'Es Kopi Susu',
    description: 'Espresso, susu segar, dan es batu. Klasik, segar, dan kaya rasa.',
    price: 18000,
    category: CATEGORIES[0],
    categoryId: 'cat-1',
    imageEmoji: '☕',
    imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-2',
    name: 'Americano',
    description: 'Espresso double shot dengan air panas. Pahit sempurna.',
    price: 15000,
    category: CATEGORIES[0],
    categoryId: 'cat-1',
    imageEmoji: '🖤',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-3',
    name: 'Cappuccino',
    description: 'Espresso dengan foam susu tebal. Klasik Italia.',
    price: 22000,
    category: CATEGORIES[0],
    categoryId: 'cat-1',
    imageEmoji: '☕',
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-4',
    name: 'Latte',
    description: 'Espresso lembut dengan susu steam berlimpah.',
    price: 22000,
    category: CATEGORIES[0],
    categoryId: 'cat-1',
    imageEmoji: '🥛',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-5',
    name: 'Kopi Tubruk',
    description: 'Kopi tradisional Indonesia, diseduh langsung tanpa filter.',
    price: 10000,
    category: CATEGORIES[0],
    categoryId: 'cat-1',
    imageEmoji: '☕',
    imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  // Non-Kopi
  {
    id: 'menu-6',
    name: 'Matcha Latte',
    description: 'Matcha premium Jepang dengan susu segar. Earthy dan creamy.',
    price: 25000,
    category: CATEGORIES[1],
    categoryId: 'cat-2',
    imageEmoji: '🍵',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-7',
    name: 'Coklat Susu',
    description: 'Cokelat belgique rich dengan susu panas atau dingin.',
    price: 20000,
    category: CATEGORIES[1],
    categoryId: 'cat-2',
    imageEmoji: '🍫',
    imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-8',
    name: 'Es Teh Manis',
    description: 'Teh hitam segar dengan gula aren. Segar dan ringan.',
    price: 8000,
    category: CATEGORIES[1],
    categoryId: 'cat-2',
    imageEmoji: '🧋',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-9',
    name: 'Jus Alpukat',
    description: 'Alpukat segar blended dengan susu dan cokelat.',
    price: 20000,
    category: CATEGORIES[1],
    categoryId: 'cat-2',
    imageEmoji: '🥑',
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80',
    isAvailable: false,
  },
  // Makanan
  {
    id: 'menu-10',
    name: 'Nasi Goreng Spesial',
    description: 'Nasi goreng dengan telur, ayam suwir, dan acar. Favorit pelanggan.',
    price: 28000,
    category: CATEGORIES[2],
    categoryId: 'cat-3',
    imageEmoji: '🍳',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-11',
    name: 'Mie Goreng',
    description: 'Mie goreng dengan sayuran segar dan bumbu spesial.',
    price: 25000,
    category: CATEGORIES[2],
    categoryId: 'cat-3',
    imageEmoji: '🍜',
    imageUrl: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-12',
    name: 'Roti Bakar Selai',
    description: 'Roti tawar panggang dengan pilihan selai cokelat atau kacang.',
    price: 15000,
    category: CATEGORIES[2],
    categoryId: 'cat-3',
    imageEmoji: '🍞',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  // Snack
  {
    id: 'menu-13',
    name: 'Kentang Goreng',
    description: 'Kentang goreng crispy dengan saus sambal dan mayo.',
    price: 18000,
    category: CATEGORIES[3],
    categoryId: 'cat-4',
    imageEmoji: '🍟',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
  {
    id: 'menu-14',
    name: 'Pisang Goreng Keju',
    description: 'Pisang goreng crispy taburan keju parut dan susu kental.',
    price: 15000,
    category: CATEGORIES[3],
    categoryId: 'cat-4',
    imageEmoji: '🍌',
    imageUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=900&q=80',
    isAvailable: true,
  },
]

export function formatRupiah(price: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
  }).format(price)
}
