'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import type { Role } from '@prisma/client'
import { createUser, resetUserPassword, toggleUserActive, updateUser } from '../actions'
import { Badge, Card, EmptyState, PageHeader, inputClass, primaryButton, secondaryButton } from '@/components/admin/UI'

type UserRow = { id: string; name: string; email: string; role: Role; isActive: boolean }
const empty = { name: '', email: '', role: 'CASHIER' as Role, password: '' }

export function UsersManager({ users }: { users: UserRow[] }) {
  const router = useRouter(); const [form, setForm] = useState(empty); const [edit, setEdit] = useState<UserRow | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); setForm(empty); setEdit(null); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Gagal menyimpan') } finally { setBusy(false) } }
  return <div><PageHeader title="Pengguna" description="Kelola akun staff, role, password, dan status akses."/>{error ? <p className="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}
    <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card className="h-fit p-5"><h2 className="font-bold">{edit ? 'Edit pengguna' : 'Tambah pengguna'}</h2><div className="mt-4 space-y-3"><input className={inputClass} placeholder="Nama lengkap" value={edit?.name ?? form.name} onChange={(e) => edit ? setEdit({...edit,name:e.target.value}) : setForm({...form,name:e.target.value})}/><input className={inputClass} type="email" placeholder="Email" value={edit?.email ?? form.email} onChange={(e) => edit ? setEdit({...edit,email:e.target.value}) : setForm({...form,email:e.target.value})}/><select className={inputClass} value={edit?.role ?? form.role} onChange={(e) => edit ? setEdit({...edit,role:e.target.value as Role}) : setForm({...form,role:e.target.value as Role})}>{['ADMIN','CASHIER','KITCHEN'].map(r=><option key={r}>{r}</option>)}</select>{!edit ? <input className={inputClass} type="password" placeholder="Password minimal 8 karakter" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/> : null}<button disabled={busy} className={`${primaryButton} w-full`} onClick={() => run(() => edit ? updateUser(edit.id, edit) : createUser(form))}>{busy ? 'Menyimpan...' : edit ? 'Simpan perubahan' : 'Tambah pengguna'}</button>{edit ? <button className={`${secondaryButton} w-full`} onClick={()=>setEdit(null)}>Batal</button> : null}</div></Card>
      <Card>{users.length === 0 ? <EmptyState title="Belum ada pengguna" description="Tambahkan akun staff pertama."/> : <div className="divide-y divide-slate-100">{users.map(user=><div key={user.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid h-11 w-11 place-items-center rounded-full bg-slate-100 font-bold text-slate-600">{user.name[0]}</div><div className="flex-1"><p className="font-semibold text-slate-900">{user.name}</p><p className="text-sm text-slate-500">{user.email}</p></div><div className="flex flex-wrap items-center gap-2"><Badge tone="blue">{user.role}</Badge><Badge tone={user.isActive?'green':'red'}>{user.isActive?'Aktif':'Nonaktif'}</Badge><button className={secondaryButton} onClick={()=>setEdit(user)}>Edit</button><button className={secondaryButton} onClick={()=>{const password=prompt('Password baru (minimal 8 karakter)'); if(password) run(()=>resetUserPassword(user.id,password))}}>Reset password</button><button className={secondaryButton} onClick={()=>run(()=>toggleUserActive(user.id))}>{user.isActive?'Nonaktifkan':'Aktifkan'}</button></div></div>)}</div>}</Card></div>
  </div>
}
