'use client'

/* eslint-disable @next/next/no-img-element -- QR image is generated by an external QR service. */
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createTable, toggleTableActive } from '../actions'
import { Badge, EmptyState, PageHeader, SectionCard, inputClass, primaryButton, secondaryButton } from '@/components/admin/UI'

type Table = { id: string; label: string; isActive: boolean }

export function TablesManager({ tables, baseUrl }: { tables: Table[]; baseUrl: string }) {
  const router = useRouter()
  const [id, setId] = useState('')
  const [label, setLabel] = useState('')
  const [error, setError] = useState('')

  async function run(action: () => Promise<void>) {
    setError('')
    try {
      await action()
      setId('')
      setLabel('')
      router.refresh()
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Gagal menyimpan meja.')
    }
  }

  return (
    <div>
      <PageHeader title="Meja & QR" description="Buat link QR per meja dan atur meja mana yang aktif menerima order." />
      {error ? <p className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</p> : null}

      <SectionCard title="Tambah meja" description="Gunakan ID stabil seperti meja-1 agar QR tetap mudah dilacak." className="mb-6">
        <div className="grid gap-3 p-5 sm:grid-cols-[1fr_1fr_auto]">
          <input className={inputClass} placeholder="ID, contoh meja-11" value={id} onChange={(event) => setId(event.target.value)} />
          <input className={inputClass} placeholder="Label meja" value={label} onChange={(event) => setLabel(event.target.value)} />
          <button className={primaryButton} onClick={() => run(() => createTable({ id, label }))}>Tambah meja</button>
        </div>
      </SectionCard>

      {tables.length === 0 ? (
        <SectionCard title="Daftar meja"><EmptyState title="Belum ada meja" description="Tambahkan meja untuk membuat URL QR." /></SectionCard>
      ) : (
        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          {tables.map((table) => {
            const url = `${baseUrl}/menu/${table.id}`
            const qr = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(url)}`
            return (
              <SectionCard key={table.id} title={table.label} description={table.id} action={<Badge tone={table.isActive ? 'green' : 'red'}>{table.isActive ? 'Aktif' : 'Nonaktif'}</Badge>}>
                <div className="flex gap-4 p-5">
                  <img src={qr} alt={`QR ${table.label}`} className="h-28 w-28 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm" />
                  <div className="min-w-0 flex-1">
                    <p className="truncate rounded-2xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500">{url}</p>
                    <div className="mt-4 flex flex-wrap gap-2">
                      <button className={secondaryButton} onClick={() => navigator.clipboard.writeText(url)}>Salin URL</button>
                      <button className={secondaryButton} onClick={() => run(() => toggleTableActive(table.id))}>{table.isActive ? 'Tutup meja' : 'Aktifkan'}</button>
                    </div>
                  </div>
                </div>
              </SectionCard>
            )
          })}
        </div>
      )}
    </div>
  )
}
